image: dockerschneider/java-jdk-ant

stages:
    - build
    - doc
    - dist

build:
    stage: build
    script:
        - ant
    only:
        - master

doc:
    stage: doc
    script:
        - ant doc
    artifacts:
        paths:
            - doc
    only:
        - master

dist:
    stage: dist
    script: ant dist
    artifacts:
        paths:
            - dist
    only:
        - master
