image: dockerschneider/java-jdk-ant

stages:
    - build
    - dist

build:
    stage: build
    script:
        - ant
    only:
        - master

doc:
    stage: build
    script:
        - ant doc
    artifacts:
        paths:
            - doc
    only:
        - master

test:
    stage: build
    script:
        - ant test
    only:
        - master
    allow_failure: yes

dist:
    stage: dist
    script: ant dist
    artifacts:
        paths:
            - dist
    only:
        - master
