image: dockerschneider/java-jdk-ant

stages:
    - build
    - test
    - dist

compile:
    stage: build
    script:
        - ant compile
    artifacts:
        paths:
            - build
        expire_in: 5 min

doc:
    stage: build
    script:
        - ant doc
    artifacts:
        paths:
            - doc
    only:
        - master
    allow_failure: yes

test:
    stage: test
    script:
        - ant test
    allow_failure: no
    dependencies:
        - compile

dist:
    stage: dist
    script: ant dist
    artifacts:
        paths:
            - dist
    only:
        - master

build_pdf:
  stage: dist
  before_script:
    - apt-get update -y
    - apt-get --assume-yes install rubygems
    - gem install kramdown
    - gem install prawn
    - gem install prawn-table
  script:
    - find . -name 'anleitung.md' -exec sh -c 'kramdown $0 --output pdf > $0.pdf' {} \;
    - mv anleitung.md.pdf anleitung.pdf
  artifacts:
    paths:
    - anleitung.pdf
  only:
    - master
