image: dockerschneider/java-jdk-ant

stages:
    - build
    - dist

build:
    stage: build
    script:
        - ant
    only:
        - master


build:
    stage: build
    script:
        - ant doc
        - cp doc public -R
    artifacts:
        paths:
            - doc
    only:
        - master

dist:
    stage: dist
    script: ant dist
    artifacts:
        paths:
            - dist
    only:
        - master
