image: dockerschneider/java-jdk-ant

stages:
    - build
    - doc
    - test
    - dist

build:
    stage: build
    script:
        - ant
    only:
        - master

doc:
    stage: doc
    script:
        - ant doc
    artifacts:
        paths:
            - doc
    only:
        - master

test:
    stage: test
    script:
        - java -cp build:FlowerWarsPP-Tester.jar BoardTester flowerwarspp.board.MainBoard
    only:
        - master
    allow_failure: yes

dist:
    stage: dist
    script: ant dist
    artifacts:
        paths:
            - dist
    only:
        - master
